postgresql.datasource.url=jdbc:postgresql://localhost:5432/jira1032
postgresql.datasource.driver.class.name=org.postgresql.Driver
postgresql.datasource.schema=public
postgresql.datasource.username=postgres
postgresql.datasource.password=root
oracle.datasource.url=jdbc:oracle:thin:@localhost:1521:ORCLCDB
oracle.datasource.driver.class.name=oracle.jdbc.driver.OracleDriver
oracle.datasource.schema=<schema, if any>
oracle.datasource.username=<username>
oracle.datasource.password=<password>
mssql.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=jira915ms;trustServerCertificate=true;
mssql.datasource.driver.class.name=com.microsoft.sqlserver.jdbc.SQLServerDriver
mssql.datasource.schema=dbo
mssql.datasource.username=sa
mssql.datasource.password=Udvitha@450
mysql.datasource.url=jdbc:mysql://localhost:3306/jira
mysql.datasource.driver.class.name=com.mysql.cj.jdbc.Driver
mysql.datasource.schema=<schema, if any>
mysql.datasource.username=<username>
mysql.datasource.password=<password>
